// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("calendar.caldav.googleResync", 1726247333);
user_pref("calendar.list.sortOrder", "8f7c8a43-c718-4d04-8816-d42430f0fd4e");
user_pref("calendar.registry.8f7c8a43-c718-4d04-8816-d42430f0fd4e.calendar-main-default", true);
user_pref("calendar.registry.8f7c8a43-c718-4d04-8816-d42430f0fd4e.calendar-main-in-composite", true);
user_pref("calendar.registry.8f7c8a43-c718-4d04-8816-d42430f0fd4e.disabled", true);
user_pref("calendar.registry.8f7c8a43-c718-4d04-8816-d42430f0fd4e.name", "Мой календарь");
user_pref("calendar.registry.8f7c8a43-c718-4d04-8816-d42430f0fd4e.type", "storage");
user_pref("calendar.registry.8f7c8a43-c718-4d04-8816-d42430f0fd4e.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Africa/Abidjan");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1726247343323");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-ru@thunderbird.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20240809151341");
user_pref("extensions.lastAppVersion", "128.1.0");
user_pref("extensions.lastPlatformVersion", "128.1.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"f2dd7d40-dada-47fa-be3d-02c2c18e0a9a\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ui-rdf.version", 43);
user_pref("mailnews.database.global.datastore.id", "fb485618-a2f3-4946-b557-597a9acaa56");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "128.1.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Важное");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Рабочее");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Личное");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "К исполнению");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Отложено");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1726247327);
user_pref("toolkit.telemetry.cachedClientID", "cda6b927-30ae-436e-9976-4c6dea9d97ef");
user_pref("toolkit.telemetry.previousBuildID", "20240809151341");
